name: nasa_clean_arch
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  dartz: ^0.9.2
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  ext_video_player: ^0.0.3
  shimmer: ^1.1.2
  sliding_up_panel: ^1.0.2
  zoom_widget: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test: ^1.15.7
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Regular-slnt=0.ttf
